"""Añadir campo apellido a Alumnos

Revision ID: 0838eb125ae3
Revises: 9015e12376ac
Create Date: 2025-05-18 21:26:47.966255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0838eb125ae3'
down_revision = '9015e12376ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Alumnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apellido', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Alumnos', schema=None) as batch_op:
        batch_op.drop_column('apellido')

    # ### end Alembic commands ###
