"""Añadir campos a alumno

Revision ID: 131061f5ba17
Revises: 0838eb125ae3
Create Date: 2025-05-18 23:52:28.970077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '131061f5ba17'
down_revision = '0838eb125ae3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Alumnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ci', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('fecha_nacimiento', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('correo', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('estado', sa.Enum('Activo', 'Inactivo', name='estado_alumno'), nullable=False))
        batch_op.create_unique_constraint(None, ['ci'])
        batch_op.create_unique_constraint(None, ['correo'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Alumnos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('estado')
        batch_op.drop_column('correo')
        batch_op.drop_column('fecha_nacimiento')
        batch_op.drop_column('ci')

    # ### end Alembic commands ###
