"""tablas profesor usuario

Revision ID: 75245867c7a8
Revises: 131061f5ba17
Create Date: 2025-05-23 19:38:33.974058

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '75245867c7a8'
down_revision = '131061f5ba17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre_usuario', sa.String(length=50), nullable=False),
    sa.Column('contraseña', sa.String(length=128), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('nombre_usuario')
    )
    op.create_table('alumnos',
    sa.Column('id_alumno', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellido', sa.String(length=50), nullable=False),
    sa.Column('ci', sa.String(length=20), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('correo', sa.String(length=120), nullable=False),
    sa.Column('estado', sa.Enum('Activo', 'Inactivo', name='estado_alumno'), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_alumno'),
    sa.UniqueConstraint('ci'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('profesores',
    sa.Column('id_profesor', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellido', sa.String(length=50), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('especialidad', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.Enum('activo', 'inactivo'), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_profesor'),
    sa.UniqueConstraint('correo')
    )
    with op.batch_alter_table('Alumnos', schema=None) as batch_op:
        batch_op.drop_index('ci')
        batch_op.drop_index('correo')

    op.drop_table('Alumnos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Alumnos',
    sa.Column('id_alumno', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('apellido', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('ci', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('fecha_nacimiento', sa.DATE(), nullable=False),
    sa.Column('correo', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('estado', mysql.ENUM('Activo', 'Inactivo'), nullable=False),
    sa.PrimaryKeyConstraint('id_alumno'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('Alumnos', schema=None) as batch_op:
        batch_op.create_index('correo', ['correo'], unique=True)
        batch_op.create_index('ci', ['ci'], unique=True)

    op.drop_table('profesores')
    op.drop_table('alumnos')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
