"""cambio nombre

Revision ID: f20469589463
Revises: 
Create Date: 2025-05-31 00:13:22.601885

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f20469589463'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inscritos',
    sa.Column('id_inscritos', sa.Integer(), nullable=False),
    sa.Column('id_alumno', sa.Integer(), nullable=False),
    sa.Column('id_curso', sa.Integer(), nullable=False),
    sa.Column('fecha_inscripcion', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id_alumno'], ['alumnos.id_alumno'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_curso'], ['cursos.id_curso'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_inscritos')
    )
    op.drop_table('matriculas')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matriculas',
    sa.Column('id_matricula', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('id_alumno', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('id_curso', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('fecha_inscripcion', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['id_alumno'], ['alumnos.id_alumno'], name='matriculas_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_curso'], ['cursos.id_curso'], name='matriculas_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_matricula'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('inscritos')
    # ### end Alembic commands ###
